CREATE USER POWERBI_SVC
  PASSWORD = '9k5369QrZhutug:>@5UP'
  DEFAULT_ROLE = POWERBI_ROLE
  DEFAULT_WAREHOUSE = DBT_PROD_WH;

GRANT ROLE POWERBI_ROLE TO USER POWERBI_SVC;

GRANT USAGE ON WAREHOUSE DBT_PROD_WH TO ROLE POWERBI_ROLE;
GRANT USAGE ON DATABASE MUSEUM_DW_PROD TO ROLE POWERBI_ROLE;
GRANT USAGE ON SCHEMA MUSEUM_DW_PROD.GOLD TO ROLE POWERBI_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA MUSEUM_DW_PROD.GOLD TO ROLE POWERBI_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA MUSEUM_DW_PROD.GOLD TO ROLE POWERBI_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MUSEUM_DW_PROD.GOLD TO ROLE POWERBI_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA MUSEUM_DW_PROD.GOLD TO ROLE POWERBI_ROLE;

ALTER USER POWERBI_SVC SET MUST_CHANGE_PASSWORD = FALSE;

GRANT SELECT ON SEMANTIC VIEW MUSEUM_DW_PROD.GOLD.SV_MUSEUM_OPERATIONS TO ROLE POWERBI_ROLE;