museum_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "om01578"
      user: "JMYERS"
      role: DBT_DEV_ROLE
      database: MUSEUM_DW_DEV
      warehouse: DBT_DEV_WH
      schema: SILVER
      threads: 4
    staging:
      type: snowflake
      account: "om01578"
      user: "JMYERS"
      role: DBT_PROD_ROLE
      database: MUSEUM_DW_STAGING
      warehouse: DBT_PROD_WH
      schema: SILVER
      threads: 8
    prod:
      type: snowflake
      account: "om01578"
      user: "JMYERS"
      role: DBT_PROD_ROLE
      database: MUSEUM_DW_PROD
      warehouse: DBT_PROD_WH
      schema: SILVER
      threads: 8
