
      begin;
    merge into "MUSEUM_DW_PROD"."SILVER"."SNAP_SF_CRM" as DBT_INTERNAL_DEST
    using "MUSEUM_DW_PROD"."SILVER"."SNAP_SF_CRM__dbt_tmp" as DBT_INTERNAL_SOURCE
    on DBT_INTERNAL_SOURCE.dbt_scd_id = DBT_INTERNAL_DEST.dbt_scd_id

    when matched
     
       and DBT_INTERNAL_DEST.dbt_valid_to is null
     
     and DBT_INTERNAL_SOURCE.dbt_change_type in ('update', 'delete')
        then update
        set dbt_valid_to = DBT_INTERNAL_SOURCE.dbt_valid_to

    when not matched
     and DBT_INTERNAL_SOURCE.dbt_change_type = 'insert'
        then insert ("CONTACT_ID", "FIRST_NAME", "LAST_NAME", "EMAIL", "PHONE", "MEMBERSHIP_TYPE", "MEMBERSHIP_STATUS", "MEMBERSHIP_START_DATE", "MEMBERSHIP_END_DATE", "DONATION_TOTAL_YTD", "LAST_DONATION_DATE", "LAST_VISIT_DATE", "PREFERRED_CONTACT_METHOD", "OPT_IN_EMAIL", "CREATED_DATE", "LAST_MODIFIED_DATE", "_LOADED_AT", "HASHDIFF", "DBT_UPDATED_AT", "DBT_VALID_FROM", "DBT_VALID_TO", "DBT_SCD_ID")
        values ("CONTACT_ID", "FIRST_NAME", "LAST_NAME", "EMAIL", "PHONE", "MEMBERSHIP_TYPE", "MEMBERSHIP_STATUS", "MEMBERSHIP_START_DATE", "MEMBERSHIP_END_DATE", "DONATION_TOTAL_YTD", "LAST_DONATION_DATE", "LAST_VISIT_DATE", "PREFERRED_CONTACT_METHOD", "OPT_IN_EMAIL", "CREATED_DATE", "LAST_MODIFIED_DATE", "_LOADED_AT", "HASHDIFF", "DBT_UPDATED_AT", "DBT_VALID_FROM", "DBT_VALID_TO", "DBT_SCD_ID")

;
    commit;
  