SELECT
    transaction_id,
    transaction_timestamp,
    item_sku,
    TRIM(item_name) AS item_name,
    TRIM(item_category) AS item_category,
    quantity,
    unit_price,
    total_amount,
    discount_amount,
    payment_method,
    cashier_id,
    terminal_id,
    LOWER(TRIM(customer_email)) AS customer_email,
    _loaded_at,
    MD5(CONCAT_WS('||',
        COALESCE(CAST(item_sku AS VARCHAR), '^^NULL^^'),
        COALESCE(CAST(item_name AS VARCHAR), '^^NULL^^'),
        COALESCE(CAST(item_category AS VARCHAR), '^^NULL^^'),
        COALESCE(CAST(quantity AS VARCHAR), '^^NULL^^'),
        COALESCE(CAST(unit_price AS VARCHAR), '^^NULL^^'),
        COALESCE(CAST(total_amount AS VARCHAR), '^^NULL^^'),
        COALESCE(CAST(discount_amount AS VARCHAR), '^^NULL^^'),
        COALESCE(CAST(payment_method AS VARCHAR), '^^NULL^^'),
        COALESCE(CAST(cashier_id AS VARCHAR), '^^NULL^^'),
        COALESCE(CAST(terminal_id AS VARCHAR), '^^NULL^^'),
        COALESCE(CAST(customer_email AS VARCHAR), '^^NULL^^')
    )) AS hashdiff
FROM {{ source('bronze', 'raw_pos_retail') }}
