SELECT
    ops.visit_date,
    dd.day_name,
    dd.month_name,
    dd.year_num,
    dd.fiscal_year,
    dd.fiscal_quarter,
    dd.is_weekend,
    ops.total_visitors,
    ops.ticket_transactions,
    ops.tickets_sold,
    ops.ticket_revenue,
    ops.ticket_discounts,
    ops.ticket_revenue - ops.ticket_discounts AS net_ticket_revenue,
    DIV0(ops.ticket_revenue, NULLIF(ops.ticket_transactions, 0)) AS ticket_aov,
    DIV0(ops.tickets_sold, NULLIF(ops.ticket_transactions, 0)) AS avg_tickets_per_txn,
    ops.retail_transactions,
    ops.retail_items_sold,
    ops.retail_revenue,
    ops.retail_discounts,
    ops.retail_revenue - ops.retail_discounts AS net_retail_revenue,
    DIV0(ops.retail_revenue, NULLIF(ops.retail_transactions, 0)) AS retail_aov,
    ops.total_revenue,
    ops.total_revenue - ops.ticket_discounts - ops.retail_discounts AS net_total_revenue,
    ops.retail_revenue_per_visitor,
    DIV0(ops.total_revenue, NULLIF(ops.total_visitors, 0)) AS revenue_per_visitor,
    ops.identified_ticket_buyers,
    DIV0(ops.identified_ticket_buyers, NULLIF(ops.ticket_transactions, 0)) AS identification_rate,
    ops.valid_scans,
    ops.rejected_scans,
    ops.gates_active
FROM {{ ref('fct_daily_operations') }} ops
LEFT JOIN {{ ref('dim_date') }} dd ON ops.visit_date = dd.date_day
